<?php

namespace App\Models;

use Chelout\RelationshipEvents\Concerns\HasBelongsToManyEvents;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;
use Spatie\MediaLibrary\Models\Media;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasBelongsToManyEvents;

    public $incrementing = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->{$model->getKeyName()} = (string) Str::uuid();
        });
    }

    public function channel()
    {
        return $this->hasOne(Channel::class);
    }

    public function subscribedChannels()
    {
        return $this->belongsToMany(Channel::class,'subscriptions')->using(Subscription::class)->withPivot('id')->withTimestamps();
    }

    public function canEditVideo(\App\Models\Media $video)
    {
        return auth()->check() && $this->id === $video->model->user_id;
    }

    public function voteVideos()
    {
        return $this->morphedByMany(\App\Models\Media::class,'votable')->withTimestamps();
    }

}
